backend:
  name: git-gateway
  branch: gatsby

publish_mode: editorial_workflow

media_folder: content/assets
public_folder: static

collections:
  - name: "blog" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content/blog"
    sort: "date:desc" # Default is title:asc
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - { label: Slug, name: "slug", widget: "string" }
      - {label: "Description", name: "description", widget: "text"}
      # - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      # - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true }
